/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 22.03.2026 11:23:32

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 10
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 20
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 85360;
#else
constexpr int kTensorArenaSize = 84336;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_CONV_2D, OP_DEPTHWISE_CONV_2D, OP_MEAN, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<4, int> tensor_dimension0 = { 4, { 1,128,128,3 } };
const TfArray<1, float> quant0_scale = { 1, { 0.0039215688593685627, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[2] = { 1, 2, };
const TfArray<1, int> tensor_dimension1 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 0, -12, 2, 35, };
const TfArray<1, int> tensor_dimension2 = { 1, { 4 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0064894710667431355, } };
const TfArray<1, int> quant2_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&quant2_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data3[4*24] = { 
  7, 37, 21, 1, -29, 6, 20, 2, -8, 5, 16, -11, 19, 8, -8, 18, 41, -13, -6, 13, -3, -20, 9, 13, 
  -17, -14, 0, 29, 36, 2, 5, -5, 16, 4, -13, -10, -2, -2, -7, 17, -41, -11, 9, 2, 4, 38, 27, 14, 
  13, -16, -25, -27, 127, 18, 19, 12, 6, 18, 9, 0, -19, -6, 21, 1, 36, -2, -41, -7, 23, 2, -30, -2, 
  -15, 20, 28, 4, 96, -1, -33, -7, 10, 11, 19, 3, -9, 11, 4, -18, 15, 23, 71, -29, -35, 3, 58, -33, 
};
const TfArray<2, int> tensor_dimension3 = { 2, { 4,24 } };
const TfArray<1, float> quant3_scale = { 1, { 0.023760531097650528, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant2_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[24] = { 0, 36, 30, 53, -36, -4, 65, -320, 0, 0, 0, -2, 0, 0, 49, -95, 30, 58, -58, 65, 12, 13, -25, 69, };
const TfArray<1, int> tensor_dimension4 = { 1, { 24 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0024573425762355328, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant2_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data5[24*20] = { 
  5, -14, -9, -22, -23, 0, -19, -23, -22, 3, 28, -22, -16, -5, 2, -26, 11, -15, -24, -23, 
  3, 11, -10, -21, 34, -3, 0, -24, -25, 22, -4, 21, 36, -116, -127, 10, 0, 25, 32, 21, 
  -10, 40, -11, -24, 2, 4, -40, -4, -7, 27, 38, 51, 1, -32, -62, -18, 35, 18, 6, 34, 
  -11, 2, -13, -29, 38, -8, 41, 24, -1, 26, -115, -72, 43, -50, -9, -16, 17, 35, -91, 40, 
  -8, 0, 10, -54, 3, 10, 10, -42, 27, 12, -9, 53, 4, -58, -53, 11, 30, 24, -11, -7, 
  3, -26, -4, -13, -34, 19, 10, 24, -17, -20, -31, 12, -20, -13, 25, 3, -11, -33, 3, -11, 
  33, 51, -17, -25, -18, 22, 13, 5, 2, 53, -42, 52, 9, 28, 44, 44, 29, -6, -46, 11, 
  -25, -6, 30, 17, -75, -69, -34, -27, -4, -35, 28, -105, 8, -12, 8, 18, 0, -17, 12, -43, 
  -23, -14, -26, -25, -6, -16, -20, 13, -8, 2, 24, -11, 22, -10, 11, 6, -10, -12, -26, 9, 
  -26, -23, -13, -12, 3, 1, -18, 6, -4, 27, -28, -20, -26, -22, -16, -7, 9, -18, 5, -15, 
  14, -17, 27, 14, 10, -17, -6, -31, -28, -18, -30, -14, -27, 29, -17, 26, -6, -27, -13, -27, 
  -20, -23, -5, -20, 27, -1, -31, -31, 0, -30, 20, 7, -5, -12, -25, -12, 26, -24, 12, -13, 
  -19, 15, 17, -31, 29, -4, -9, 10, -26, -7, -20, 0, -26, 10, 24, -4, 3, -23, -24, -29, 
  4, -2, 18, 21, -9, -16, -2, -30, 6, -1, -29, -20, -27, -14, 14, 11, -27, -31, -17, -30, 
  -11, 1, -16, 12, 9, 8, -15, 33, 43, 36, -26, -90, -12, 27, 35, -4, 25, 5, -48, 6, 
  -15, -36, -34, -1, -15, 18, 35, -4, 21, -9, 8, 59, -9, 47, 46, 1, -44, -28, 44, -22, 
  -4, -15, 20, -45, -13, 6, -8, -32, 25, 13, 4, 100, -11, -15, -49, 39, 14, 31, 26, 36, 
  -33, -10, -25, 33, -18, 31, 33, 39, -28, -17, 25, 4, -1, 26, 6, 21, 37, 35, 38, 6, 
  48, 29, 23, -10, 4, -16, 17, -20, 9, -13, -50, -39, 40, 49, 17, 17, 26, -33, -55, 19, 
  3, 12, 17, -43, 46, -4, -14, -26, 39, 10, -50, -10, 26, -82, -96, -11, 39, 32, -12, 3, 
  -8, 9, 21, 17, 19, 22, 6, 10, 48, 26, -38, -97, 51, -1, 26, 4, 32, 21, -52, -13, 
  -32, 25, 21, 12, -4, 26, 44, 7, 21, -19, -94, -117, 28, -9, 40, 12, -20, 5, -99, 37, 
  34, -4, 6, -34, 30, 4, 5, -25, 47, 16, -70, -5, -1, 28, 6, -11, 31, 1, -82, 9, 
  43, 14, 15, -34, 18, 33, -29, -4, 37, 3, -21, 29, 15, 0, -16, 44, 43, 13, -70, 9, 
};
const TfArray<2, int> tensor_dimension5 = { 2, { 24,20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.011847089976072311, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant2_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[20] = { -111, -12, -12, -15, 6, 0, -33, -10, -20, 38, -82, 12, 19, -15, 0, 4, 24, 82, -50, 40, };
const TfArray<1, int> tensor_dimension6 = { 1, { 20 } };
const TfArray<20, float> quant6_scale = { 20, { 0.0025668893940746784, 0.0024054460227489471, 0.001690406003035605, 0.0031167881097644567, 0.0047993054613471031, 0.0020925721619278193, 0.0034708743914961815, 0.0031186721753329039, 0.0030306151602417231, 0.0028125762473791838, 0.0040809665806591511, 0.004534558393061161, 0.0040965140797197819, 0.0044998195953667164, 0.0047401180490851402, 0.002432272769510746, 0.0028150873258709908, 0.0031801748555153608, 0.0050808587111532688, 0.0031862468458712101, } };
const TfArray<20, int> quant6_zero = { 20, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[20*1*1*16] = { 
  /* [0][0][][] */ -4,-88,15,-64,-21,-9,83,59,31,61,-54,77,-101,-45,-12,127, 
  /* [1][0][][] */ -4,0,56,-43,-100,102,123,41,53,127,8,-20,-92,-36,0,-75, 
  /* [2][0][][] */ 25,42,23,-31,21,-25,-77,-24,18,7,-52,-127,72,12,32,-75, 
  /* [3][0][][] */ 13,18,106,7,-50,127,67,108,21,94,55,-53,93,36,11,-12, 
  /* [4][0][][] */ 18,6,10,35,-19,40,-12,24,11,127,-22,29,-35,21,-10,-21, 
  /* [5][0][][] */ 33,18,-59,4,-11,-15,16,-24,-29,-37,-13,57,127,11,44,-28, 
  /* [6][0][][] */ -3,-10,71,58,-52,127,-14,76,26,50,-9,-28,29,35,30,-25, 
  /* [7][0][][] */ 46,23,127,14,-68,102,-5,76,17,103,87,4,94,15,25,-74, 
  /* [8][0][][] */ -74,-21,3,-30,-75,127,100,69,17,54,-19,42,-7,49,16,26, 
  /* [9][0][][] */ 53,-25,-2,21,17,-127,-7,-66,32,-71,-9,61,15,0,-51,29, 
  /* [10][0][][] */ -69,-35,-3,54,100,69,11,7,-83,-80,67,-12,127,34,29,7, 
  /* [11][0][][] */ -22,-18,-118,-113,-47,-52,7,-38,46,-127,-50,42,-55,-17,-25,6, 
  /* [12][0][][] */ 7,-2,45,62,3,83,9,26,-19,127,-37,39,-56,20,-30,3, 
  /* [13][0][][] */ -24,-24,127,-6,-14,78,89,47,-24,57,29,35,38,17,19,52, 
  /* [14][0][][] */ -1,-11,127,-11,-27,90,68,111,9,77,1,-17,101,4,-2,-49, 
  /* [15][0][][] */ 3,11,-27,-101,52,-127,56,-29,11,-55,25,62,-8,-25,56,-24, 
  /* [16][0][][] */ 9,7,-48,-22,-6,-127,53,35,31,1,-11,89,-50,40,50,31, 
  /* [17][0][][] */ 51,36,-102,17,45,-127,-103,-98,29,-29,10,69,57,-49,-46,-42, 
  /* [18][0][][] */ -10,-50,-19,32,88,62,10,7,-31,-39,46,-35,127,-31,-31,10, 
  /* [19][0][][] */ 67,65,-6,9,-71,-95,-56,-75,61,-10,16,-32,-127,-29,-35,-120, 
};
const TfArray<4, int> tensor_dimension7 = { 4, { 20,1,1,16 } };
const TfArray<20, float> quant7_scale = { 20, { 0.0062793227843940258, 0.0058843875303864479, 0.0041352016851305962, 0.0076245279051363468, 0.011740431189537048, 0.0051190117374062538, 0.0084907207638025284, 0.0076291365548968315, 0.0074137249030172825, 0.0068803410977125168, 0.0099831754341721535, 0.011092786677181721, 0.0100212087854743, 0.011007806286215782, 0.011595642194151878, 0.0059500131756067276, 0.0068864836357533932, 0.0077795893885195255, 0.012429188936948776, 0.0077944430522620678, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { -33, 247, -7, -34, -17, -65, -8, -75, 209, -87, -377, 274, 8, -23, -625, -83, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 0.00045050779590383172, 0.00039786534034647048, 0.0014988471521064639, 0.00076840189285576344, 0.00088994397083297372, 0.00040422804886475205, 0.00078552402555942535, 0.00069525931030511856, 0.0005235777935013175, 0.00041941815288737416, 0.00044665558380074799, 0.00044873377191834152, 0.00056842603953555226, 0.00018403670401312411, 0.00013022296479903162, 0.00070186750963330269, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[1*3*3*16] = { 
  /* [0][0][][] */ 11,22,78,60,64,68,76,77,58,-86,34,27,-127,114,-86,84, 10,85,95,109,127,-49,125,52,51,41,121,120,-14,110,10,71, -13,84,43,41,65,84,79,-10,127,84,60,80,69,127,-3,95, 
  /* [0][1][][] */ 76,1,112,63,57,53,97,9,26,-127,-28,37,-79,-67,24,110, 127,127,127,127,118,-122,127,65,44,-17,83,86,-3,-47,-109,63, 38,58,99,73,103,-117,70,52,107,117,120,31,-3,-100,-89,89, 
  /* [0][2][][] */ 19,-18,81,96,46,127,110,-127,59,-118,99,53,26,-36,-43,127, 81,105,115,126,116,-77,125,-90,53,-25,82,81,49,-68,-72,76, 89,20,79,75,66,-112,71,-51,65,48,127,127,62,-119,-127,94, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 1,3,3,16 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0037270963657647371, 0.003291579894721508, 0.012400113046169281, 0.0063570658676326275, 0.00736259575933218, 0.0033442191779613495, 0.0064987190999090672, 0.0057519502006471157, 0.0043316115625202656, 0.003469888586550951, 0.0036952265072613955, 0.0037124196533113718, 0.0047026458196341991, 0.0015225542010739446, 0.0010773476678878069, 0.0058066206984221935, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 3 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[16] = { 159, 287, 547, -145, -293, 348, 323, -1, 504, -144, -71, 219, 740, -17, -324, 252, };
const TfArray<16, float> quant10_scale = { 16, { 0.00064170552650466561, 0.0004709491622634232, 0.00062144477851688862, 0.00041838700417429209, 0.00038922484964132309, 0.0010497689945623279, 0.00052070902893319726, 0.0006094758864492178, 0.00037407196941785514, 0.00090151350013911724, 0.00060780701460316777, 0.00052303745178505778, 0.0011621697340160608, 0.00024749874137341976, 0.00030297954799607396, 0.00041632118518464267, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[16*1*1*12] = { 
  /* [0][0][][] */ 32,19,39,-96,24,-26,-98,31,32,4,127,2, 
  /* [1][0][][] */ 28,54,3,-127,-30,-63,-82,93,73,102,104,5, 
  /* [2][0][][] */ 14,-20,-127,-75,-37,-5,53,4,-5,-24,72,52, 
  /* [3][0][][] */ -16,20,110,-69,97,-18,93,-127,-94,28,27,-63, 
  /* [4][0][][] */ -41,-117,60,9,61,-88,62,-92,-88,-30,-127,-19, 
  /* [5][0][][] */ -2,52,75,-11,-61,-12,-127,6,29,51,34,-38, 
  /* [6][0][][] */ 42,0,-86,-65,127,93,61,21,-44,-17,-9,47, 
  /* [7][0][][] */ 18,47,-71,25,58,-16,127,43,17,36,13,53, 
  /* [8][0][][] */ 100,97,-37,127,92,66,-105,69,21,-54,-74,87, 
  /* [9][0][][] */ 25,-40,84,32,56,2,-127,-58,-12,-5,-26,20, 
  /* [10][0][][] */ -51,-25,57,-74,64,-16,127,-11,-31,-10,3,16, 
  /* [11][0][][] */ 31,65,-70,127,56,55,-25,78,41,14,-35,48, 
  /* [12][0][][] */ 0,61,25,-50,-34,32,-78,86,127,113,-43,-8, 
  /* [13][0][][] */ -85,-74,-118,-2,54,76,-93,-5,25,-127,-41,-56, 
  /* [14][0][][] */ -53,-28,43,59,-91,-8,-100,-127,-14,71,-103,-117, 
  /* [15][0][][] */ -50,41,-51,127,0,-86,-70,93,14,-50,7,-60, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 16,1,1,12 } };
const TfArray<16, float> quant11_scale = { 16, { 0.008756173774600029, 0.006426176056265831, 0.0084797125309705734, 0.0057089570909738541, 0.0053110350854694843, 0.014324265532195568, 0.0071051577106118202, 0.0083163958042860031, 0.0051042716950178146, 0.012301295064389706, 0.0082936231046915054, 0.00713692931458354, 0.015857990831136703, 0.0033771595917642117, 0.004134204238653183, 0.0056807687506079674, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data12[12] = { 2635, 728, -192, -669, -109, 2221, -2850, 2014, 1953, -42, 690, 2665, };
const TfArray<1, int> tensor_dimension12 = { 1, { 12 } };
const TfArray<12, float> quant12_scale = { 12, { 5.0399539759382606e-05, 6.1422811995726079e-05, 0.00010422252671560273, 0.00010415053111501038, 0.00011219193402212113, 4.9577400204725564e-05, 0.00011557685502339154, 0.000116108545626048, 0.00010876196029130369, 7.2386697866022587e-05, 0.0001161163963843137, 8.9530585682950914e-05, } };
const TfArray<12, int> quant12_zero = { 12, { 0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant12 = { (TfLiteFloatArray*)&quant12_scale, (TfLiteIntArray*)&quant12_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data13[1*3*3*12] = { 
  /* [0][0][][] */ -15,102,125,101,42,-106,108,-127,-127,-127,2,123, 60,114,84,105,51,-96,102,-108,-97,-35,-10,56, -4,118,55,127,79,-116,89,-16,-67,-93,-81,127, 
  /* [0][1][][] */ 88,87,119,56,37,-75,112,-75,-72,-68,35,109, 109,91,98,66,90,-58,89,-84,-11,-3,19,63, 127,55,114,103,70,-1,104,-1,-19,-46,-127,83, 
  /* [0][2][][] */ 114,78,96,84,80,127,88,-104,-86,-70,34,126, 41,127,94,116,127,-1,127,-96,-39,-36,-31,64, 38,34,127,68,111,26,106,-42,-31,-15,-50,103, 
};
const TfArray<4, int> tensor_dimension13 = { 4, { 1,3,3,12 } };
const TfArray<12, float> quant13_scale = { 12, { 0.002862054156139493, 0.0034880361054092646, 0.0059185167774558067, 0.0059144282713532448, 0.0063710780814290047, 0.0028153671883046627, 0.0065632984042167664, 0.0065934918820858002, 0.006176298949867487, 0.0041106459684669971, 0.0065939375199377537, 0.0050842012278735638, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant12_zero, 3 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data14[12] = { 2044, 507, 705, 103, 616, 401, -993, 461, -1180, -398, 1578, 1111, };
const TfArray<12, float> quant14_scale = { 12, { 7.6469164923764765e-05, 0.00018994406855199486, 0.00018365037976764143, 0.00017814255261328071, 0.00012738289660774171, 9.3628033937420696e-05, 0.00018936044943984598, 0.00013559231592807919, 0.00012738475925289094, 0.00014848967839498073, 0.00012709586007986218, 0.00022723095025867224, } };
const TfLiteAffineQuantization quant14 = { (TfLiteFloatArray*)&quant14_scale, (TfLiteIntArray*)&g0::quant12_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data15[12*1*1*8] = { 
  /* [0][0][][] */ -81,-60,40,-55,17,127,-1,72, 
  /* [1][0][][] */ -39,37,8,-71,-31,4,127,45, 
  /* [2][0][][] */ -36,-43,42,74,7,-59,127,51, 
  /* [3][0][][] */ -23,13,100,-127,-13,-12,123,38, 
  /* [4][0][][] */ 79,-97,-27,58,127,-72,8,19, 
  /* [5][0][][] */ 63,6,32,123,-14,-10,115,127, 
  /* [6][0][][] */ -120,-121,-69,127,73,-77,91,-5, 
  /* [7][0][][] */ -35,-127,46,61,-5,-105,40,-74, 
  /* [8][0][][] */ 127,5,62,71,80,-117,87,-95, 
  /* [9][0][][] */ -57,-22,-127,58,40,-65,-78,-16, 
  /* [10][0][][] */ -71,36,101,106,-30,67,127,92, 
  /* [11][0][][] */ 23,36,-76,-27,56,-20,-127,-3, 
};
const TfArray<4, int> tensor_dimension15 = { 4, { 12,1,1,8 } };
const TfArray<12, float> quant15_scale = { 12, { 0.0045016282238066196, 0.011181729845702648, 0.010811230167746544, 0.010486992076039314, 0.0074988454580307007, 0.005511745810508728, 0.011147373355925083, 0.0079821217805147171, 0.0074989553540945053, 0.008741370402276516, 0.0074819480068981647, 0.013376754708588123, } };
const TfLiteAffineQuantization quant15 = { (TfLiteFloatArray*)&quant15_scale, (TfLiteIntArray*)&g0::quant12_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data16[8] = { -371, 5323, -49, 6564, 362, 2088, 1320, 3924, };
const TfArray<1, int> tensor_dimension16 = { 1, { 8 } };
const TfArray<8, float> quant16_scale = { 8, { 5.5518117733299732e-05, 5.828106077387929e-05, 7.3211951530538499e-05, 4.6493205445585772e-05, 3.8203521398827434e-05, 8.3885541243944317e-05, 3.5774792195297778e-05, 2.4797809601295739e-05, } };
const TfArray<8, int> quant16_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant16 = { (TfLiteFloatArray*)&quant16_scale, (TfLiteIntArray*)&quant16_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data17[1*3*3*8] = { 
  /* [0][0][][] */ 34,-104,62,-39,30,-127,-97,31, 13,-95,127,3,124,-84,-127,58, 127,-127,-30,-11,106,-116,26,95, 
  /* [0][1][][] */ 61,-91,58,13,92,-102,-86,37, 9,-67,97,-50,122,-44,-41,111, 90,-70,94,-17,127,-89,90,88, 
  /* [0][2][][] */ -25,-84,70,-35,19,-83,73,-91, -55,-89,48,-127,47,-65,93,59, -7,-74,111,-61,120,-103,34,127, 
};
const TfArray<4, int> tensor_dimension17 = { 4, { 1,3,3,8 } };
const TfArray<8, float> quant17_scale = { 8, { 0.006674792617559433, 0.0070069734938442707, 0.0088020740076899529, 0.0055897519923746586, 0.0045931055210530758, 0.010085331276059151, 0.0043011060915887356, 0.0029813733417540789, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant16_zero, 3 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data18[8] = { 5384, -8166, -3118, -4312, -7069, -2500, 6931, 11938, };
const TfArray<8, float> quant18_scale = { 8, { 2.44424409174826e-05, 1.1840747902169824e-05, 1.5459505448234268e-05, 1.1820910913229454e-05, 1.2192951544420794e-05, 1.3705317542189732e-05, 1.5130558495002333e-05, 1.2295492524572182e-05, } };
const TfLiteAffineQuantization quant18 = { (TfLiteFloatArray*)&quant18_scale, (TfLiteIntArray*)&g0::quant16_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data19[8*3*3*3] = { 
  /* [0][0][][] */ -34,18,20, -127,-2,20, -100,-34,-10, 
  /* [0][1][][] */ -51,8,-17, -33,15,-35, -49,-9,-20, 
  /* [0][2][][] */ 45,31,24, 36,51,43, 50,39,21, 
  /* [1][0][][] */ 91,-62,35, 14,-67,109, 42,-22,80, 
  /* [1][1][][] */ 59,-86,63, 87,-74,62, 20,-29,30, 
  /* [1][2][][] */ 53,-113,-38, 16,-127,-80, 49,-1,-95, 
  /* [2][0][][] */ -16,12,51, 92,92,44, 46,90,81, 
  /* [2][1][][] */ -80,53,-48, -71,-63,-127, 3,-5,37, 
  /* [2][2][][] */ -28,-18,-75, -46,-63,-112, 16,16,-2, 
  /* [3][0][][] */ 3,51,-21, 49,-14,-52, -80,127,-19, 
  /* [3][1][][] */ -78,98,-7, -11,103,-111, -61,117,-88, 
  /* [3][2][][] */ 8,36,-111, -87,84,-113, 31,54,-12, 
  /* [4][0][][] */ 90,-48,-113, 31,21,-66, 112,-81,-3, 
  /* [4][1][][] */ 36,-91,-48, 75,19,-22, 12,38,-80, 
  /* [4][2][][] */ 42,-37,-107, 31,-30,-127, 83,-78,-83, 
  /* [5][0][][] */ 44,-127,13, 42,-84,39, 22,-31,70, 
  /* [5][1][][] */ 116,-81,-19, 10,-46,62, -30,-119,4, 
  /* [5][2][][] */ -27,-51,78, 70,-58,-21, 69,-22,1, 
  /* [6][0][][] */ -44,-127,-102, -31,-56,29, -51,55,-26, 
  /* [6][1][][] */ -20,14,-51, -72,64,61, 25,127,76, 
  /* [6][2][][] */ -96,32,-59, 56,96,20, 2,124,29, 
  /* [7][0][][] */ -3,73,-52, -43,-69,-47, -73,75,-127, 
  /* [7][1][][] */ 91,1,20, -56,-58,4, -82,-14,-77, 
  /* [7][2][][] */ 7,10,66, -48,77,27, 31,107,76, 
};
const TfArray<4, int> tensor_dimension19 = { 4, { 8,3,3,3 } };
const TfArray<8, float> quant19_scale = { 8, { 0.006232821848243475, 0.0030193906277418137, 0.0039421734400093555, 0.0030143321491777897, 0.0031092024873942137, 0.0034948557149618864, 0.0038582922425121069, 0.0031353502999991179, } };
const TfLiteAffineQuantization quant19 = { (TfLiteFloatArray*)&quant19_scale, (TfLiteIntArray*)&g0::quant16_zero, 0 };
const TfArray<4, int> tensor_dimension20 = { 4, { 1,64,64,8 } };
const TfArray<1, float> quant20_scale = { 1, { 0.0083175795152783394, } };
const TfLiteAffineQuantization quant20 = { (TfLiteFloatArray*)&quant20_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension21 = { 4, { 1,32,32,8 } };
const TfArray<1, float> quant21_scale = { 1, { 0.016987001523375511, } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension22 = { 4, { 1,32,32,12 } };
const TfArray<1, float> quant22_scale = { 1, { 0.017609568312764168, } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension23 = { 4, { 1,16,16,12 } };
const TfArray<1, float> quant23_scale = { 1, { 0.073286063969135284, } };
const TfLiteAffineQuantization quant23 = { (TfLiteFloatArray*)&quant23_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension24 = { 4, { 1,16,16,16 } };
const TfArray<1, float> quant24_scale = { 1, { 0.12087366729974747, } };
const TfLiteAffineQuantization quant24 = { (TfLiteFloatArray*)&quant24_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension25 = { 4, { 1,8,8,16 } };
const TfArray<1, float> quant25_scale = { 1, { 0.408784419298172, } };
const TfLiteAffineQuantization quant25 = { (TfLiteFloatArray*)&quant25_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension26 = { 4, { 1,8,8,20 } };
const TfArray<1, float> quant26_scale = { 1, { 0.65571838617324829, } };
const TfLiteAffineQuantization quant26 = { (TfLiteFloatArray*)&quant26_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<2, int> tensor_dimension27 = { 2, { 1,20 } };
const TfArray<1, float> quant27_scale = { 1, { 0.20742161571979523, } };
const TfLiteAffineQuantization quant27 = { (TfLiteFloatArray*)&quant27_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<2, int> tensor_dimension28 = { 2, { 1,24 } };
const TfArray<1, float> quant28_scale = { 1, { 0.27311977744102478, } };
const TfLiteAffineQuantization quant28 = { (TfLiteFloatArray*)&quant28_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<2, int> tensor_dimension29 = { 2, { 1,4 } };
const TfArray<1, float> quant29_scale = { 1, { 0.059756483882665634, } };
const TfArray<1, int> quant29_zero = { 1, { -93 } };
const TfLiteAffineQuantization quant29 = { (TfLiteFloatArray*)&quant29_scale, (TfLiteIntArray*)&quant29_zero, 0 };
const TfArray<1, float> quant30_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant30 = { (TfLiteFloatArray*)&quant30_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteConvParams opdata0 = { kTfLitePaddingSame, 2,2, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs0 = { 3, { 0,19,18 } };
const TfArray<1, int> outputs0 = { 1, { 20 } };
const TfLiteDepthwiseConvParams opdata1 = { kTfLitePaddingSame, 2,2, 1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 20,17,16 } };
const TfArray<1, int> outputs1 = { 1, { 21 } };
const TfLiteConvParams opdata2 = { kTfLitePaddingValid, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs2 = { 3, { 21,15,14 } };
const TfArray<1, int> outputs2 = { 1, { 22 } };
const TfLiteDepthwiseConvParams opdata3 = { kTfLitePaddingSame, 2,2, 1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs3 = { 3, { 22,13,12 } };
const TfArray<1, int> outputs3 = { 1, { 23 } };
const TfLiteConvParams opdata4 = { kTfLitePaddingValid, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs4 = { 3, { 23,11,10 } };
const TfArray<1, int> outputs4 = { 1, { 24 } };
const TfLiteDepthwiseConvParams opdata5 = { kTfLitePaddingSame, 2,2, 1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 24,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 25 } };
const TfLiteConvParams opdata6 = { kTfLitePaddingValid, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs6 = { 3, { 25,7,6 } };
const TfArray<1, int> outputs6 = { 1, { 26 } };
const ALIGN(1) uint8_t opdata7[1] = { 0,  }; /* op type 40=MEAN */
const TfArray<2, int> inputs7 = { 2, { 26,1 } };
const TfArray<1, int> outputs7 = { 1, { 27 } };
const TfLiteFullyConnectedParams opdata8 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs8 = { 3, { 27,5,4 } };
const TfArray<1, int> outputs8 = { 1, { 28 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 28,3,2 } };
const TfArray<1, int> outputs9 = { 1, { 29 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 29 } };
const TfArray<1, int> outputs10 = { 1, { 30 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 49152, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 96, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 96, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 480, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 320, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 144, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 192, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data12, (TfLiteIntArray*)&g0::tensor_dimension12, 48, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data13, (TfLiteIntArray*)&g0::tensor_dimension13, 108, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data14, (TfLiteIntArray*)&g0::tensor_dimension12, 48, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant14))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data15, (TfLiteIntArray*)&g0::tensor_dimension15, 96, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant15))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data16, (TfLiteIntArray*)&g0::tensor_dimension16, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant16))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data17, (TfLiteIntArray*)&g0::tensor_dimension17, 72, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data18, (TfLiteIntArray*)&g0::tensor_dimension16, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant18))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data19, (TfLiteIntArray*)&g0::tensor_dimension19, 216, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant19))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 49152), (TfLiteIntArray*)&g0::tensor_dimension20, 32768, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant20))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 12288), (TfLiteIntArray*)&g0::tensor_dimension21, 8192, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension22, 12288, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 12288), (TfLiteIntArray*)&g0::tensor_dimension23, 3072, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant23))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension24, 4096, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant24))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 4096), (TfLiteIntArray*)&g0::tensor_dimension25, 1024, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant25))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension26, 1280, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant26))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 1360), (TfLiteIntArray*)&g0::tensor_dimension27, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant27))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension28, 24, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant28))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 32), (TfLiteIntArray*)&g0::tensor_dimension29, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant29))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension29, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant30))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_CONV_2D, OP_DEPTHWISE_CONV_2D, OP_CONV_2D, OP_DEPTHWISE_CONV_2D, OP_CONV_2D, OP_DEPTHWISE_CONV_2D, OP_CONV_2D, OP_MEAN, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 31, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  30, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_929067_7_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 31;
  for (size_t i = 0; i < 31; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_DEPTHWISE_CONV_2D] = Register_DEPTHWISE_CONV_2D();
  registrations[OP_MEAN] = Register_MEAN();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_929067_7_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_929067_7_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_929067_7_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_929067_7_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
